### ISSUE TITLE
Support for up-comming --mode library option

### ISSUE THREAD

**Issue by renarsvilnis** [tom-grey/typedoc-plugin-markdown#117]
Hi,
just started using `typedoc` and `typedoc`plugin-markdown` today and it is exactly what I was looking for. Thanks for the work on it! 👏

I was looking into auto-generating docs for an npm module. Noticed TypeDoc is developing currently a new mode called `--mode module`, which is aimed at my use case where you output a single file.
Branch: https://github.com/TypeStrong/typedoc/tree/library-mode

But had an issue using it in combination with `typedoc-plugin-markdown`:

```bash
> typedoc --plugin typedoc-plugin-markdown --theme markdown --mode library --out ./docs/ ./src/index.ts

Loaded plugin typedoc-plugin-markdown

Using TypeScript 3.8.3 from /path/to/project/node_modules/typescript/lib
/path/to/project/node_modules/typedoc-plugin-markdown/dist/theme.js:213
            project.groups.forEach(group => {
                           ^

TypeError: Cannot read property 'forEach' of undefined
    at MarkdownTheme.getNavigation (/path/to/project/node_modules/typedoc-plugin-markdown/dist/theme.js:213:28)
    at NavigationPlugin.onBeginRenderer (/path/to/project/node_modules/typedoc/dist/lib/output/plugins/NavigationPlugin.js:19:44)
    at triggerApi (/path/to/project/node_modules/typedoc/dist/lib/utils/events.js:259:33)
    at triggerApi (/path/to/project/node_modules/typedoc/dist/lib/utils/events.js:110:13)
    at Renderer.trigger (/path/to/project/node_modules/typedoc/dist/lib/utils/events.js:252:13)
    at Renderer.render (/path/to/project/node_modules/typedoc/dist/lib/output/renderer.js:33:14)
    at CliApplication.generateDocs (/path/to/project/node_modules/typedoc/dist/lib/application.js:93:23)
    at CliApplication.bootstrap (/path/to/project/node_modules/typedoc/dist/lib/cli.js:48:26)
    at Object.<anonymous> (/path/to/project/node_modules/typedoc/bin/typedoc:5:5)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
```

**Comment by renarsvilnis** [comment]
Actually had an issue that `./src/index.ts` the file didn't exist. The mode actually works.
Just through the error, I couldn't identify the issue.
